### ISSUE TITLE
join() fails with ExitCodeException=255

### ISSUE THREAD

**Issue by oza** [hortonworks/spark-native-yarn#16]
A following query fails with spar-native-yarn:
```
val rdd1 = sc.textFile("hdfs:///user/ozawa/randomText20GB").flatMap(line => line.split(" ")).map(word => (word, 1))
val rdd2 = sc.textFile("hdfs:///user/ozawa/randomText20GB").flatMap(line => line.split(" ")).map(word => (word, 1))
rdd1.join(rdd2, 28).saveAsTextFile("hdfs:///user/ozawa/outs/tez/join/1")
```

```
14/11/27 01:27:02 INFO rpc.DAGClientRPCImpl: DAG: State: FAILED Progress: 63.16% TotalTasks: 76 Succeeded: 48 Running: 0 Failed: 1 Killed: 27
14/11/27 01:27:02 INFO rpc.DAGClientRPCImpl: VertexStatus: VertexName: 1 Progress: 100% TotalTasks: 24 Succeeded: 24 Running: 0 Failed: 0 Killed: 0
14/11/27 01:27:02 INFO rpc.DAGClientRPCImpl: VertexStatus: VertexName: 2 Progress: 100% TotalTasks: 24 Succeeded: 24 Running: 0 Failed: 0 Killed: 0
14/11/27 01:27:02 INFO rpc.DAGClientRPCImpl: VertexStatus: VertexName: 0 Progress: 0% TotalTasks: 28 Succeeded: 0 Running: 0 Failed: 1 Killed: 27
14/11/27 01:27:02 INFO rpc.DAGClientRPCImpl: DAG completed. FinalState=FAILED
14/11/27 01:27:02 INFO tez.DAGBuilder: DAG execution complete
14/11/27 01:27:02 ERROR tez.DAGBuilder: DAG diagnostics: [Vertex failed, vertexName=0, vertexId=vertex_1417036912823_0003_1_02, diagnostics=[Task failed, taskId=task_1417036912823_0003_1_02_000006, diagnostics=[TaskAttempt 0 failed, info=[Container container_1417036912823_0003_01_000002 finished with diagnostics set to [Container failed. Exception from container-launch: ExitCodeException exitCode=255: 
ExitCodeException exitCode=255: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:702)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:195)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:300)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:81)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by olegz** [comment]
With join being refactored, the problem can no longer be reproduced. An additional test was added (see commit message above).
