### ISSUE TITLE
Failing a job with attempting to add duplicate resource

### ISSUE THREAD

**Issue by oza** [hortonworks/spark-native-yarn#19]
Built for Hadoop 2.5.2. It fails with ```org.apache.tez.dag.api.TezUncheckedException: Attempting to add duplicate resource: hadoop-common-2.5.2.jar```

```
14/12/06 15:05:12 INFO tez.Utils: DAG: {1=(stage: 1; vertex:0; input:name:hdfs:///user/ozawa/randomText100GB; path:hdfs:/user/ozawa/randomText100GB), 0=(stage: 0; vertex:1; input:[1])}
14/12/06 15:05:12 INFO tez.DAGBuilder: Submitting generated DAG to YARN/Tez cluster
14/12/06 15:05:12 INFO client.TezClient: Submitting DAG application with id: application_1417526888598_0030
14/12/06 15:05:12 INFO client.TezClientUtils: Using tez.lib.uris value from configuration: hdfs://10.240.144.103:9000/apps/tez,hdfs://10.240.144.103:9000/apps/tez/lib
14/12/06 15:05:12 INFO client.TezClient: Tez system stage directory hdfs://10.240.144.103:9000/tmp/ozawa/tez/staging/.tez/application_1417526888598_0030 doesn't exist and is created
org.apache.tez.dag.api.TezUncheckedException: Attempting to add duplicate resource: hadoop-common-2.5.2.jar
        at org.apache.tez.common.TezCommonUtils.addAdditionalLocalResources(TezCommonUtils.java:314)
        at org.apache.tez.dag.api.DAG.createDag(DAG.java:668)
        at org.apache.tez.client.TezClientUtils.prepareAndCreateDAGPlan(TezClientUtils.java:639)
        at org.apache.tez.client.TezClientUtils.createApplicationSubmissionContext(TezClientUtils.java:569)
        at org.apache.tez.client.TezClient.submitDAGApplication(TezClient.java:680)
        at org.apache.tez.client.TezClient.submitDAGApplication(TezClient.java:657)
        at org.apache.tez.client.TezClient.submitDAG(TezClient.java:349)
        at org.apache.spark.tez.DAGBuilder.run(DAGBuilder.java:164)
        at org.apache.spark.tez.DAGBuilder.access$000(DAGBuilder.java:60)
        at org.apache.spark.tez.DAGBuilder$1.execute(DAGBuilder.java:148)
        at org.apache.spark.tez.TezDelegate.submitApplication(TezDelegate.scala:83)
        at org.apache.spark.tez.TezJobExecutionContext.runJob(TezJobExecutionContext.scala:157)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1092)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1107)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1128)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:81)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:878)
        at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:792)
```

**Comment by olegz** [comment]
Closing since its Tez related. Please re-open if problem re-apears
